# GitLab configuration
gitlab:
  image:
    repository: gitlab/gitlab-ce
    tag: "latest"  # Use the latest GitLab CE version
  replicaCount: 1
  ingress:
    enabled: true
    host: "gitlab.example.com"
    path: /
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  config:
    externalUrl: "http://gitlab.example.com"
    gitlab:
      omniauth:
        enabled: false

# PostgreSQL configuration
postgresql:
  image:
    repository: postgres
    tag: "14"  # Tag for PostgreSQL version 14
  replicaCount: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  storage:
    size: "10Gi"  # Size of the storage for PostgreSQL

# PostgreSQL container template configuration
containers:
  - name: postgres
    image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
    env:
      - name: POSTGRES_USER
        value: "gitlab_user"
      - name: POSTGRES_PASSWORD
        value: "Muruga@123"
      - name: POSTGRES_DB
        value: "gitlab_db"
