gitlab:
  image:
    repository: gitlab/gitlab-ce
    tag: "latest"
  replicaCount: 1
  ingress:
    enabled: true
    host: "gitlab.example.com"
    path: /
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  config:
    externalUrl: "http://gitlab.example.com"
    gitlab:
      omniauth:
        enabled: false
postgresql:
  image:
    repository: postgres
    tag: "15-alpine"
  replicaCount: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  storage:
    size: "10Gi"
