apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: {{ .Values.postgresql.image }}
        ports:
        - containerPort: {{ .Values.postgresql.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database | quote }}

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-storage

      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
