apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: {{ .Values.gitlab.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: "{{ .Values.gitlab.image.repository }}:{{ .Values.gitlab.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIAUTH_ENABLED
              value: "{{ .Values.gitlab.config.gitlab.omniauth.enabled }}"
            - name: GITLAB_EXTERNAL_URL
              value: "{{ .Values.gitlab.config.externalUrl }}"
