apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.gitlab.port }}
  selector:
    app: gitlab
