apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.gitlab.ingress.host }}
      http:
        paths:
          - path: {{ .Values.gitlab.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: gitlab-service
                port:
                  number: 80
